# Generated by Django 2.1.1 on 2018-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=128, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=256, verbose_name='URL地址')),
                ('api_param_value', models.CharField(max_length=1024, verbose_name='请求参数和值')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=64, null=True, verbose_name='请求方法')),
                ('api_result', models.CharField(max_length=256, verbose_name='预期结果')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Api_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('api_test_desc', models.CharField(max_length=64, null=True, verbose_name='描述')),
                ('api_tester', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('api_test_result', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流程场景接口',
            },
        ),
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=128, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=256, verbose_name='URL地址')),
                ('api_paramvalue', models.CharField(max_length=1024, verbose_name='请求参数和值')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=64, null=True, verbose_name='请求方法')),
                ('api_result', models.CharField(max_length=256, verbose_name='预期结果')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
