# Generated by Django 2.1.1 on 2018-10-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='Modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_platform.Modules'),
        ),
        migrations.AddField(
            model_name='api_test',
            name='Modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_platform.Modules'),
        ),
        migrations.AddField(
            model_name='api_step',
            name='api_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Api_test'),
        ),
    ]
