# Generated by Django 2.1.1 on 2018-10-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_case_name', models.CharField(max_length=256, verbose_name='用例名称')),
                ('web_test_result', models.BooleanField(verbose_name='测试结果')),
                ('web_tester', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Modules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_platform.Modules')),
            ],
            options={
                'verbose_name': 'web测试用例',
                'verbose_name_plural': 'web测试用例',
            },
        ),
        migrations.CreateModel(
            name='Web_case_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_case_name', models.CharField(max_length=256, verbose_name='测试用例标题')),
                ('web_test_setp', models.CharField(max_length=256, verbose_name='测试步骤')),
                ('web_testobj_name', models.CharField(max_length=256, verbose_name='测试对象名称描述')),
                ('web_find_method', models.CharField(max_length=256, verbose_name='定位方式')),
                ('web_evelement', models.CharField(max_length=512, verbose_name='控件元素')),
                ('web_test_data', models.CharField(max_length=512, verbose_name='测试数据')),
                ('web_assert_data', models.CharField(max_length=128, verbose_name='验证数据')),
                ('web_test_result', models.BooleanField(max_length=32, verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('web_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webui.Web_case')),
            ],
        ),
    ]
